name: Setup SMB Server on Windows

on:
  workflow_dispatch:

jobs:
  setupSMB:
    runs-on: windows-latest

    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with: 
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
            
      - name: Enable SMB Sharing
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart

      - name: Share Folder
        run: |
          New-SmbShare -Name "SharedFolder" -Path "D:\a\repo-first-study-brocli\repo-first-study-brocli\" -FullAccess "Everyone"

      - name: Set Folder Permissions
        run: |
          $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
          Set-LocalUser -Name "runneradmin" -Password $password
          $acl = Get-Acl -Path "D:\a\repo-first-study-brocli\repo-first-study-brocli\"
          $rule = New-Object System.Security.AccessControl.FileSystemAccessRule("Everyone","FullControl","Allow")
          $acl.SetAccessRule($rule)
          Set-Acl -Path "D:\a\repo-first-study-brocli\repo-first-study-brocli\" -AclObject $acl
