name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba
  
      - name: Configure Samba
        run: |
          echo ${{ secrets.SAMBA_PASS }} | sudo adduser sambauser
          sudo mkdir -p /home/sambauser/shared_folder
          sudo chmod 777 /home/sambauser/shared_folder
          sudo chmod +x main.sh
          sudo echo "
          [share]
          path = /home/sambauser/shared_folder
          writeable = yes
          create mask = 0777
          directory mask = 0777
          public = yes
        " | sudo tee /etc/samba/smb.conf
  
      - name: Restart Samba
        run: sudo service smbd restart
  
      - name: Test Samba
        run: sudo ./main.sh
