name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          sudo apt-get install -y smbclient
          sudo adduser sambauser
          echo ${{ secrets.SAMBA_PASS }} | sudo smbpasswd -s -a sambauser
          sudo mkdir -p /home/sambauser/shared_folder
          sudo chmod 777 /home/sambauser/shared_folder
          sudo chown sambauser /home/sambauser/shared_folder
          sudo chgrp sambauser /home/sambauser/shared_folder
          sudo chmod +x main.sh
          echo "
          [shared_folder]
            path = /home/sambauser/shared_folder
            readonly = no
            inherit permission = yes
          " | sudo tee /etc/samba/smb.conf
    
      - name: Restart Samba
        run: |
          sudo service smbd restart
          sudo ufw allow samba
  
      - name: Test Samba
        run: sudo ./main.sh
