name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          sudo apt-get install -y smbclient
          sudo adduser --disabled-password sambauser
          sudo usermod -p ${{ secrets.SAMBA_PASS }} sambauser
          echo -e "${{ secrets.SAMBA_PASS }}\n${{ secrets.SAMBA_PASS }}" | sudo smbpasswd -a sambauser
          sudo usermod -aG sambashare sambauser
          sudo mkdir -p /home/sambauser/share
          sudo chmod 777 /home/sambauser/share
          sudo chown sambauser /home/sambauser/share
          sudo chgrp sambashare /home/sambauser/share
          sudo chmod +x main.sh
          echo "
          [share]
            path = /home/sambauser/share
            readonly = no
            writeable = yes
            create mask = 0777
            directory mask = 0777
            guest ok = yes
            inherit permission = yes
            bind interfaces only = yes
            interfaces = 127.0.0.1
          " | sudo tee /etc/samba/smb.conf
    
      - name: Restart Samba
        run: |
          sudo service smbd restart
          sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 445 -j REDIRECT --to-port 445  --match comment --comment "Explain."
          sudo ufw allow samba
  
      - name: Test Samba
        run: sudo ./main.sh
