name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          sudo apt-get install -y smbclient
          echo ${{ secrets.SAMBA_PASS }} || passwd --stdin runner
          echo ${{ secrets.SAMBA_PASS }} || sudo smbpasswd -a runner
          sudo mkdir -p /srv/samba/share
          sudo chmod 777 /srv/samba/share
          sudo chown runner /srv/samba/share
          sudo chgrp runner /srv/samba/share
          sudo chmod +x main.sh
          echo "
          [share]
            path = /srv/samba/share
            readonly = no
            writeable = yes
            create mask = 0777
            directory mask = 0777
            inherit permission = yes
          " | sudo tee /etc/samba/smb.conf
    
      - name: Restart Samba
        run: |
          sudo service smbd restart
          sudo ufw allow samba
  
      - name: Test Samba
        run: sudo ./main.sh
