name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo cloudflared service install ${{ secrets.CF_ID }}
          sudo systemctl start cloudflared

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          sudo mkdir -p /srv/samba/share
          sudo chmod 777 /srv/samba/share
          sudo chmod +x main.sh
          echo "
          [share]
          path = /srv/samba/share
          writeable = yes
          create mask = 0777
          directory mask = 0777
          public = yes
          " | sudo tee /etc/samba/smb.conf
    
      - name: Restart Samba
        run: sudo service smbd restart
  
      - name: Test Samba
        run: sudo ./main.sh
