name: SMB Setup

on:
  push:
    branches: [ main ]

jobs:
  setup-smb:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: ZeroTier
      uses: zerotier/github-action@v1.0.1
      with: 
        network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

    - name: SetupSMB Server
      run: |
        Set-SmbServerConfiguration -EnableSMB1Protocol $true
        Start-SmbServer -Auto
        $ipv4Address = $networkAdapters[0].IPAddress[0]
        New-SmbShare -Name "GitHubActions" -Path "D:\a\repo-first-study-brocli\repo-first-study-brocli\" -FullAccess "Everyone"
        Set-SmbShare -Name "GitHubActions" -CachingMode Manual -ContinuouslyAvailable $true
