name: samba server

on:
  workflow_dispatch:

jobs:
  runDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}

      - name: Install Samba
        run: |
          sudo apt-get update
          sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          sudo mkdir -p /srv/samba/share
          sudo chmod 777 /srv/samba/share
          sudo chmod +x main.sh
          sudo apt-get install -y smbclient
          sudo useradd -r -s /bin/false ${{ secrets.SAMBA_USER }}
          echo ${{ secrets.SAMBA_PASSWORD }} | sudo smbpasswd -s -a ${{ secrets.SAMBA_USER }}
          echo "
          [share]
          path = /srv/samba/share
          writeable = yes
          create mask = 0777
          directory mask = 0777
          public = yes
          " | sudo tee /etc/samba/smb.conf
    
      - name: Restart Samba
        run: |
          sudo service smbd restart
          sudo ufw allow samba
  
      - name: Test Samba
        run: sudo ./main.sh
